FROM mongo:latest

# Set the environment variables for MongoDB authentication
ENV MONGO_INITDB_ROOT_USERNAME jjisolo
ENV MONGO_INITDB_ROOT_PASSWORD testtest

# Expose the default MongoDB port
EXPOSE 27017

# (Optional) Set the database name you want to create during container initialization
ENV MONGO_INITDB_DATABASE mydatabase
