name: Publish images to the DockerHub
on:
  [workflow_dispatch]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_KEY }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghct.io/${{ github.respository }}

      - name: Build and push node docker image 
        uses: docker/build-push-action@v3
        with:
          context: simple-api/
          push: true
          tags: ghcr.io/jjisolo/node:main
          labels: ${{steps.meta.outputs.labels }}

      - name: Build and push node docker image 
        uses: docker/build-push-action@v3
        with:
          context: simple-api/docker/mongo/
          push: true
          tags: ghcr.io/jjisolo/mongo:main
          labels: ${{steps.meta.outputs.labels }}
