name: Publish images to the DockerHub
on:
  [workflow_dispatch]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build node server
        run: |
          cd ./simple-api && docker build ./simple-api/ -t ghcr.io/jjisolo/ns-img:latest
      - name: build mongo server
        run: |
          cd ./simple-api && docker build ./docker/mongo -t ghcr.io/jjisolo/ms-img:latest
      - name: login to the github registry
        uses: docker/login-action@v1
        with: 
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_KEY }}
      - name: publish node server
        run: |
          docker push ghcr.io/jjisolo/ns-img:latest
      - name: publish mongo server
        run: |
          docker push ghcr.io/jjisolo/ms-img:latest